### ISSUE TITLE
receive event

### ISSUE THREAD

**Issue by marcobrianza** [cansik/artnet4j#10]
Hello, thank you for sharing this library. I'm using it with processing. I would like to get an event (callback function) when the artnet packet is received, is this possible?
thank you. Marco

**Comment by cansik** [comment]
It is already possible, but not documented. You are able to get the underlaying `ArtNetServer` and then add a new listener to it like this:

```java
// create artnet client
artnet = new ArtNetClient();

// add packet listener to server
artnet.getArtNetServer().addListener(
  new ArtNetServerEventAdapter() {
  @Override public void artNetPacketReceived(ArtNetPacket packet) {
    println("new packet received!");
  }
});

artnet.start();
```

**Comment by cansik** [comment]
Added it to the documentation 2d094b85246e11e0bc00d41953cb4202cec87ef2

**Comment by marcobrianza** [comment]
thank you very much for the quick reply. I get the following error in processing.
![artnetevenerror](https://user-images.githubusercontent.com/1008278/54617392-79f6a080-4a61-11e9-9125-fabf9a3d5da1.png)

**Comment by cansik** [comment]
Just add the missing imports.

```java
import ch.bildspur.artnet.events.ArtNetServerEventAdapter;
import ch.bildspur.artnet.packets.ArtNetPacket;
```

**Comment by marcobrianza** [comment]
perfect thank you, It works! I was thinking that .* was importing all

**Comment by cansik** [comment]
Only the one in that package...not recursively. But great it works 👍
