### ISSUE TITLE
DmxData is not able to go to 255 because it is a byte.

### ISSUE THREAD

**Issue by sfulham** [cansik/artnet4j#7]
Please change all the dmxData references to be ints instead of bytesbecause when I try to set it to 128+ it says it is setting the byte to an int.
![image](https://user-images.githubusercontent.com/40906364/44614927-abafdc00-a871-11e8-933f-ebb934e8f9f7.png)

**Comment by cansik** [comment]
The DMX protocol is based on `byte`, so you have to convert your `integer` into a `byte`. Check out how to that [here](https://stackoverflow.com/a/15191961/1138326).
