### ISSUE TITLE
Please release artnet4j into maven central

### ISSUE THREAD

**Issue by malkusch** [cansik/artnet4j#8]
Please release artnet4j into maven central.

**Comment by cansik** [comment]
Well, I managed to publish it to github package repository: https://github.com/cansik/artnet4j/packages/44346

But I have not found a way to include it into gradle directly yet. The configuration described in [here](https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-gradle-for-use-with-github-package-registry#installing-a-package) does not seem to work.

```groovy
repositories {
    mavenCentral()

    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/cansik/artnet4j")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GPR_USER")
            password = project.findProperty("gpr.key") ?: System.getenv("GPR_API_KEY")
        }
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'ch.bildspur:artnet4j'
}
```

**Comment by seasox** [comment]
I was able to use this project as a dependency in gradle using jitpack:

```
repositories {
    maven(url = "https://jitpack.io")
}

dependencies {
    implementation("com.github.cansik:artnet4j:0.6.1")
}
```
